const Item = require("../models/Item");

async function itemSeed() {
  const items = [
    {
      name: "Radiator Coolant",
      brandName: "Prestone",
      description: "Protects engine from overheating",
      quantity: 120,
      status_id: 1,
      main_category_id: 4,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE23456",
      LKB_No: "LKB65432",
      price: 24.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Tire Inflator",
      brandName: "Slime",
      description: "Compact tire inflator with gauge",
      quantity: 80,
      status_id: 2,
      main_category_id: 5,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE11234",
      LKB_No: "LKB43121",
      price: 39.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Spark Plug Wrench",
      brandName: "Craftsman",
      description: "Tool for replacing spark plugs",
      quantity: 90,
      status_id: 1,
      main_category_id: 6,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE44578",
      LKB_No: "LKB87345",
      price: 12.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Timing Belt",
      brandName: "Gates",
      description: "Durable timing belt for specific models",
      quantity: 45,
      status_id: 3,
      main_category_id: 3,
      is_feature: true,
      is_universal: false,
      OE_NO: "OE56789",
      LKB_No: "LKB98765",
      price: 49.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Battery Charger",
      brandName: "NOCO",
      description: "Smart battery charger for vehicles",
      quantity: 65,
      status_id: 1,
      main_category_id: 5,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE99876",
      LKB_No: "LKB67899",
      price: 59.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Brake Fluid",
      brandName: "Castrol",
      description: "High-performance brake fluid",
      quantity: 100,
      status_id: 1,
      main_category_id: 4,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE23489",
      LKB_No: "LKB98234",
      price: 8.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Leather Seat Conditioner",
      brandName: "Meguiar's",
      description: "Restores and protects leather seats",
      quantity: 200,
      status_id: 5,
      main_category_id: 6,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE77865",
      LKB_No: "LKB66788",
      price: 15.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Car Jack",
      brandName: "Powerbuilt",
      description: "2-ton hydraulic floor jack",
      quantity: 50,
      status_id: 1,
      main_category_id: 6,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE11223",
      LKB_No: "LKB33211",
      price: 79.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Head Gasket Set",
      brandName: "Fel-Pro",
      description: "Comprehensive head gasket kit for specific engines",
      quantity: 30,
      status_id: 1,
      main_category_id: 3,
      is_feature: true,
      is_universal: false,
      OE_NO: "OE66789",
      LKB_No: "LKB56789",
      price: 99.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Cabin Air Filter",
      brandName: "FRAM",
      description: "Filter to keep the air clean inside the car",
      quantity: 70,
      status_id: 2,
      main_category_id: 2,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE55899",
      LKB_No: "LKB99855",
      price: 19.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Fuel Injector",
      brandName: "Bosch",
      description: "Precision fuel injector for specific engines",
      quantity: 40,
      status_id: 1,
      main_category_id: 3,
      is_feature: true,
      is_universal: false,
      OE_NO: "OE88990",
      LKB_No: "LKB99088",
      price: 79.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Car Battery",
      brandName: "Optima",
      description: "High-performance battery for longer life",
      quantity: 60,
      status_id: 1,
      main_category_id: 5,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE12356",
      LKB_No: "LKB65123",
      price: 129.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Wheel Lug Nuts",
      brandName: "McGard",
      description: "Heavy-duty lug nuts for secure wheel fitting",
      quantity: 120,
      status_id: 1,
      main_category_id: 4,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE99882",
      LKB_No: "LKB22899",
      price: 24.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Power Steering Fluid",
      brandName: "Lucas",
      description: "Power steering fluid for smooth handling",
      quantity: 100,
      status_id: 1,
      main_category_id: 4,
      is_feature: false,
      is_universal: true,
      OE_NO: "OE44552",
      LKB_No: "LKB22544",
      price: 11.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      name: "Turbocharger",
      brandName: "Garrett",
      description: "Performance turbocharger for specific models",
      quantity: 10,
      status_id: 4,
      main_category_id: 3,
      is_feature: true,
      is_universal: false,
      OE_NO: "OE66790",
      LKB_No: "LKB99001",
      price: 499.99,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ];

  await Item.bulkCreate(items);
  console.log("Inserted items");
}

module.exports = itemSeed;
