const Item = require("../models/Item");

async function itemSeed() {
  const items = [
    {
      name: "Car Cover for Toyota Camry",
      brandName: "Generic Brand",
      main_category_id: 1,
      isFeature: false,
      isUniversal: true,
      OE_NO: "BB-fdlfjasl",
      price: 50.0,
    },
    {
      name: "Leather Seat Covers for Honda Accord",
      brandName: "Luxury Covers",
      main_category_id: 2,
      isFeature: true,
      isUniversal: false,
      OE_NO: "djflasfjlds",
      price: 120.0,
    },
    {
      name: "Performance Exhaust System",
      brandName: "High Performance Parts",
      main_category_id: 3,
      isFeature: true,
      isUniversal: false,
      OE_NO: "dafjdlsfj1",
      price: 300.0,
    },
    {
      name: "OEM Brake Pads for Chevrolet Impala",
      brandName: "Chevy OEM Parts",
      main_category_id: 4,
      isFeature: false,
      isUniversal: false,
      OE_NO: "Bkjdaslfjdlka",
      price: 80.0,
    },
    {
      name: "Diagnostic Scanner Tool",
      brandName: "TechTools",
      main_category_id: 5,
      isFeature: true,
      isUniversal: true,
      OE_NO: "lajdlkfds2343",
      price: 150.0,
    },
    {
      name: "All-Weather Floor Mats for Ford F-150",
      brandName: "ToughGuard",
      main_category_id: 6,
      isFeature: false,
      isUniversal: true,
      OE_NO: "BG243FDSK9",
      price: 65.0,
    },
    {
      name: "LED Headlights for BMW 3 Series",
      brandName: "BrightVision",
      main_category_id: 1,
      isFeature: true,
      isUniversal: false,
      OE_NO: "HDJ123BWM",
      price: 200.0,
    },
    {
      name: "Car Battery Charger",
      brandName: "PowerPlus",
      main_category_id: 2,
      isFeature: false,
      isUniversal: true,
      OE_NO: "PPBC3241",
      price: 85.0,
    },
    {
      name: "Engine Oil for Honda Civic",
      brandName: "SuperLube",
      main_category_id: 3,
      isFeature: true,
      isUniversal: false,
      OE_NO: "EOHC12345",
      price: 35.0,
    },
    {
      name: "Windshield Wiper Blades",
      brandName: "RainMaster",
      main_category_id: 4,
      isFeature: false,
      isUniversal: true,
      OE_NO: "RMWW7890",
      price: 25.0,
    },
    {
      name: "High-Performance Air Filter",
      brandName: "AirFlowMax",
      main_category_id: 5,
      isFeature: true,
      isUniversal: false,
      OE_NO: "AFM1234",
      price: 45.0,
    },
    {
      name: "Bluetooth Car Stereo",
      brandName: "SoundWave",
      main_category_id: 6,
      isFeature: true,
      isUniversal: true,
      OE_NO: "SWCS0012",
      price: 180.0,
    },
    {
      name: "Steering Wheel Cover",
      brandName: "GripGuard",
      main_category_id: 1,
      isFeature: false,
      isUniversal: true,
      OE_NO: "GGSW7891",
      price: 20.0,
    },
    {
      name: "Portable Tire Inflator",
      brandName: "AirPro",
      main_category_id: 2,
      isFeature: true,
      isUniversal: true,
      OE_NO: "APTI4567",
      price: 60.0,
    },
    {
      name: "Roof Rack for SUVs",
      brandName: "RackMaster",
      main_category_id: 3,
      isFeature: false,
      isUniversal: false,
      OE_NO: "RMSUV123",
      price: 220.0,
    },
    {
      name: "HID Conversion Kit",
      brandName: "BrightLights",
      main_category_id: 4,
      isFeature: true,
      isUniversal: true,
      OE_NO: "BLHID567",
      price: 90.0,
    },
    {
      name: "Engine Coolant for Audi A4",
      brandName: "CoolGuard",
      main_category_id: 5,
      isFeature: false,
      isUniversal: false,
      OE_NO: "CGA41234",
      price: 40.0,
    },
    {
      name: "Rearview Mirror with Dash Cam",
      brandName: "ViewCam",
      main_category_id: 6,
      isFeature: true,
      isUniversal: true,
      OE_NO: "VCMIR789",
      price: 120.0,
    },
    {
      name: "Cargo Liner for SUVs",
      brandName: "ToughLiner",
      main_category_id: 1,
      isFeature: false,
      isUniversal: false,
      OE_NO: "TL789SUV",
      price: 75.0,
    },
    {
      name: "Side Step Bars for Trucks",
      brandName: "StepUp",
      main_category_id: 2,
      isFeature: true,
      isUniversal: false,
      OE_NO: "SUB123TRK",
      price: 250.0,
    },
    {
      name: "Rear Spoiler for Sports Cars",
      brandName: "SpeedyStyle",
      main_category_id: 3,
      isFeature: true,
      isUniversal: false,
      OE_NO: "RS456SPRT",
      price: 300.0,
    },
    {
      name: "Windshield Sun Shade",
      brandName: "CoolGuard",
      main_category_id: 4,
      isFeature: false,
      isUniversal: true,
      OE_NO: "CGSUN123",
      price: 25.0,
    },
    {
      name: "Car Dash Cover",
      brandName: "DashProtect",
      main_category_id: 5,
      isFeature: true,
      isUniversal: false,
      OE_NO: "DPCD5678",
      price: 70.0,
    },
    {
      name: "Wheel Lock Kit",
      brandName: "SecureWheels",
      main_category_id: 6,
      isFeature: false,
      isUniversal: true,
      OE_NO: "SWLK9012",
      price: 55.0,
    },
    {
      name: "Performance Chip Tuning",
      brandName: "PowerTuner",
      main_category_id: 1,
      isFeature: true,
      isUniversal: false,
      OE_NO: "PCT5678",
      price: 200.0,
    },
    {
      name: "Car Cover for SUVs",
      brandName: "WeatherGuard",
      main_category_id: 2,
      isFeature: false,
      isUniversal: false,
      OE_NO: "WCSUV1234",
      price: 100.0,
    },
    {
      name: "LED Taillights for Trucks",
      brandName: "BrightTail",
      main_category_id: 3,
      isFeature: true,
      isUniversal: false,
      OE_NO: "BTLT567",
      price: 150.0,
    },
    {
      name: "Portable Jump Starter",
      brandName: "PowerBoost",
      main_category_id: 4,
      isFeature: false,
      isUniversal: true,
      OE_NO: "PBJUMP123",
      price: 80.0,
    },
    {
      name: "Car Vacuum Cleaner",
      brandName: "CleanCar",
      main_category_id: 5,
      isFeature: false,
      isUniversal: true,
      OE_NO: "CCVAC5678",
      price: 45.0,
    },
    {
      name: "Hydraulic Floor Jack",
      brandName: "LiftPro",
      main_category_id: 6,
      isFeature: true,
      isUniversal: true,
      OE_NO: "LPFJ789",
      price: 130.0,
    },
  ];

  await Item.bulkCreate(items);
  console.log("Inserted 30 items");
}

itemSeed();

module.exports = itemSeed;
